cursor #e4e2e0
cursor_text_color #c3c8c1

foreground            #e4e2e0
background            #131412
selection_foreground  #2b322c
selection_background  #c1c9c0
url_color             #b6ccba

# black
color0   #343533
color8   #c3c8c1

# red
color1   #ffb4ab
color9   #93000a

# green
color2   #e3bdc0
color10  #e3bdc0

# yellow
color3   #c1c9c0
color11  #c1c9c0

# blue
color4   #b6ccba
color12  #b6ccba

# magenta
color5   #667a6b
color13  #414942

# cyan
color6   #e3bdc0
color14  #8d6d70

# white
color7   #c3c8c1
color15  #e4e2e0
