cursor #f3ded7
cursor_text_color #dec0b6

foreground            #f3ded7
background            #1b110d
selection_foreground  #502412
selection_background  #feb69c
url_color             #ffb59b

# black
color0   #3f322e
color8   #dec0b6

# red
color1   #ffb4ab
color9   #93000a

# green
color2   #66d5ef
color10  #66d5ef

# yellow
color3   #feb69c
color11  #feb69c

# blue
color4   #ffb59b
color12  #ffb59b

# magenta
color5   #e56e3f
color13  #6b3926

# cyan
color6   #66d5ef
color14  #1a9eb6

# white
color7   #dec0b6
color15  #f3ded7
