###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$fileManager = nautilus --new-window
# $fileManager = kitty -e "yazi"
$menu = rofi -show drun -ml-row-left ScrollUp -ml-row-right ScrollDown -ml-row-up ScrollLeft -ml-row-down ScrollRight
$browser = firefox
$sysmonitor = missioncenter
# $screenshot = hyprshot -m output -o /home/alex/Pictures/Screenshots/
