################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=eDP-1 , 2520x1680@90 , 0x0 , 1.5
# eDP-1 logical size: 2520/1.5 = 1680, HDMI-A-1 logical width: 1920.
# Centered above eDP-1 => x = (1680 - 1920) / 2 = -120; y = -1080.
monitor=HDMI-A-1 , 1920x1080@100 , -120x-1080 , 1
