#############################
### LOCAL WINDOW LAYOUTS ###
#############################

# This file is managed by ~/.config/hypr/scripts/save_window_state.sh.
# Generated rules are appended below and reloaded automatically.


# BEGIN AUTORULE 2bd751eac2800b739e29ae4cc13bc4d8668dca06
# Saved 2026-06-07T11:24:01+03:00 for class=org.telegram.desktop
windowrule = float 1, match:class ^(org\.telegram\.desktop)$
windowrule = size 470 632, match:class ^(org\.telegram\.desktop)$
windowrule = move 605 276, match:class ^(org\.telegram\.desktop)$
# END AUTORULE 2bd751eac2800b739e29ae4cc13bc4d8668dca06
