###############
### PLUGINS ###
###############

plugin {
    overview {
        drawActiveWorkspace = true
        showNewWorkspace = false
        showEmptyWorkspace = false
        exitOnSwitch = true
        workspaceActiveBorder = $primary
        workspaceInactiveBorder = $background
        workspaceActiveBackground = rgba(33333366)

    }
}
