##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

workspace = 1 , monitor:eDP-1 , default:true , persistent:true
workspace = 2 , monitor:eDP-1
workspace = 3 , monitor:eDP-1 
workspace = 4 , monitor:eDP-1 
workspace = 5 , monitor:eDP-1 
workspace = 6 , monitor:eDP-1 
workspace = 7 , monitor:eDP-1 
workspace = 8 , monitor:eDP-1 
workspace = 9 , monitor:eDP-1 
workspace = 10 , monitor:eDP-1 
workspace = 11 , monitor:HDMI-A-1 , persistent:true
workspace = 12 , monitor:HDMI-A-1
workspace = 13 , monitor:HDMI-A-1
workspace = 14 , monitor:HDMI-A-1
workspace = 15 , monitor:HDMI-A-1
workspace = 16 , monitor:HDMI-A-1
workspace = 17 , monitor:HDMI-A-1
workspace = 18 , monitor:HDMI-A-1
workspace = 19 , monitor:HDMI-A-1
workspace = 20 , monitor:HDMI-A-1
workspace = name:Windows, monitor:eDP-1

# Ignore maximize requests from apps. You'll probably like this. 
windowrule = suppressevent maximize, class:.*

# JetBrains IDE (often XWayland) can cause border flicker with `input:follow_mouse = 1`
# because tooltip windows may temporarily receive focus. Fighting focus via `nofocus` breaks dialogs.
# Keep JetBrains tooltip windows from stealing focus.
# In your case the tooltip has an auto-title like `winl496` (XWayland), which causes focus thrash and makes
# the tooltip disappear immediately. Match those auto-titles instead of blanket `floating:1` rules.
windowrulev2 = nofocus, class:^(jetbrains-(studio|idea))$, xwayland:1, title:^(win[a-z]*[0-9]+)$
windowrule = float, size 1000 700, class:org.kde.kdeconnect.app
windowrule = float, size 1000 700, class:org.kde.kdeconnect.sms
windowrule = float, size 1000 700, class:org.kde.kdeconnect-indicator
windowrule = float, size 879 879, class:org.pulseaudio.pavucontrol
windowrule = float, size 879 879, class:blueman-manager
windowrule = float, center, class:xdg-desktop-portal-gtk # Portal GTK dialogs (Open/Save) open as centered floating popups
windowrule = opacity 0.80 0.75,class:org.gnome.Nautilus
windowrule = opacity 0.95 0.85,class:code
windowrule = opacity 0.95 0.85,class:org.telegram.desktop
windowrule = opacity 0.80 0.85,initialTitle:yandex-music
windowrule = workspace name:Windows silent,class:^(Microsoft Windows)$
windowrule = workspace name:Windows,class:^(xfreerdp)$
windowrulev2 = workspace 10, class:^(exe)$, initialtitle:^(DEFAULT PROJECT)$
windowrule = idleinhibit fullscreen, class:.*
# windowrule = workspace special:magic silent, float, size 682 882, move 82 151, class:org.telegram.desktop
windowrule = workspace special:magic silent, class:Throne
windowrule = pseudo, class:Throne
windowrule = opacity 0.85 0.75, class:Throne
windowrulev2 = workspace 11, class:^(ktalk)$

# RDP Office apps
windowrule = workspace name:Windows,class:^(msword-rdp)$
windowrule = workspace name:Windows,class:^(msexcel-rdp)$
windowrule = workspace name:Windows,class:^(mspowerpoint-rdp)$
