# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#25130f"

# Title color for boxes
theme[title]="#780800"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#780800"

# Background color of selected item in processes box
theme[selected_bg]="#780800"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#50322d"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#003a71"

# Cpu box outline color
theme[cpu_box]="#6f4e48"

# Memory/disks box outline color
theme[mem_box]="#6f4e48"

# Net up/down box outline color
theme[net_box]="#6f4e48"

# Processes box outline color
theme[proc_box]="#6f4e48"

# Box divider line and small boxes line color
theme[div_line]="#8f6a64"

# Temperature graph colors
theme[temp_start]="#780800"
theme[temp_mid]="#780800"
theme[temp_end]="#7b0007"

# CPU graph colors
theme[cpu_start]="#780800"
theme[cpu_mid]="#780800"
theme[cpu_end]="#7b0007"

# Mem/Disk free meter
theme[free_start]="#780800"
theme[free_mid]=""
theme[free_end]="#ce422d"

# Mem/Disk cached meter
theme[cached_start]="#003a71"
theme[cached_mid]=""
theme[cached_end]="#0073d8"

# Mem/Disk available meter
theme[available_start]="#780800"
theme[available_mid]=""
theme[available_end]="#e41800"

# Mem/Disk used meter
theme[used_start]="#7b0007"
theme[used_mid]=""
theme[used_end]="#d8332d"

# Download graph colors
theme[download_start]="#780800"
theme[download_mid]="#780800"
theme[download_end]="#003a71"

# Upload graph colors
theme[upload_start]="#780800"
theme[upload_mid]="#780800"
theme[upload_end]="#003a71"