# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#1a1715"

# Title color for boxes
theme[title]="#4d331e"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#45372d"

# Background color of selected item in processes box
theme[selected_bg]="#4d331e"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#423831"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#203d42"

# Cpu box outline color
theme[cpu_box]="#5f544c"

# Memory/disks box outline color
theme[mem_box]="#5f544c"

# Net up/down box outline color
theme[net_box]="#5f544c"

# Processes box outline color
theme[proc_box]="#5f544c"

# Box divider line and small boxes line color
theme[div_line]="#7d7169"

# Temperature graph colors
theme[temp_start]="#45372d"
theme[temp_mid]="#4d331e"
theme[temp_end]="#7b0007"

# CPU graph colors
theme[cpu_start]="#45372d"
theme[cpu_mid]="#4d331e"
theme[cpu_end]="#7b0007"

# Mem/Disk free meter
theme[free_start]="#45372d"
theme[free_mid]=""
theme[free_end]="#817064"

# Mem/Disk cached meter
theme[cached_start]="#203d42"
theme[cached_mid]=""
theme[cached_end]="#375459"

# Mem/Disk available meter
theme[available_start]="#4d331e"
theme[available_mid]=""
theme[available_end]="#664933"

# Mem/Disk used meter
theme[used_start]="#7b0007"
theme[used_mid]=""
theme[used_end]="#d8332d"

# Download graph colors
theme[download_start]="#45372d"
theme[download_mid]="#4d331e"
theme[download_end]="#203d42"

# Upload graph colors
theme[upload_start]="#45372d"
theme[upload_mid]="#4d331e"
theme[upload_end]="#203d42"